Document: git-lfs-server
Title: Debian git-lfs-server Manual
Author: <insert document author here>
Abstract: This manual describes what git-lfs-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-lfs-server/git-lfs-server.sgml.gz

Format: postscript
Files: /usr/share/doc/git-lfs-server/git-lfs-server.ps.gz

Format: text
Files: /usr/share/doc/git-lfs-server/git-lfs-server.text.gz

Format: HTML
Index: /usr/share/doc/git-lfs-server/html/index.html
Files: /usr/share/doc/git-lfs-server/html/*.html
